{
	"_Type": "Action.Type.Message",
	"Message": "Dispatch Id {#ActionResults:GenerateDispatchID/data/DispatchId} generate successfully",
	"Title": "Success",
	"OKCaption": "Ok",
	"OnOK": "/BoxDispatch/Rules/GenerateDispatchSuccessOk.js"
}