{
	"_Type": "Action.Type.Message",
	"Message": "Are you sure to stop loading of boxes for dispatch ID {#Page:Main/#ClientData/HeaderDetail/DispatchId} ?",
	"Title": "Stop Loading",
	"OKCaption": "Yes",
	"OnOK": "/BoxDispatch/Rules/StopLoad.js",
	"CancelCaption": "No"
}