{
	"_Type": "Action.Type.Message",
	"ActionResult": {
		"_Name": "StopBoxLoadingSuccess"
	},
	"Message": "{#Page:Main/#ClientData/HeaderDetail/Count} boxes scanned successfully for dispatch ID {#Page:Main/#ClientData/HeaderDetail/DispatchId}",
	"Title": "Success",
	"OKCaption": "Ok",
	"OnOK": "/BoxDispatch/Actions/NavToMain.action"
}