{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"ActionResult": {
		"_Name": "StopBoxLoading"
	},
	"OnFailure": "/BoxDispatch/Actions/FailureMessage.action",
	"OnSuccess": "/BoxDispatch/Actions/StopBoxLoadingSuccess.action",
	"ShowActivityIndicator": true,
	"Target": {
		"Service": "/BoxDispatch/Services/DISPATCH.service",
		"EntitySet": "DispatchDetailsSet"
	},
	"Properties": {
		"BoxId": "",
		"TransporterId": "#Page:Main/#ClientData/HeaderDetail/Transporter",
		"VehicleNo": "#Page:Main/#ClientData/HeaderDetail/VehicleNo",
		"DriverName": "#Page:Main/#ClientData/HeaderDetail/DriverName",
		"DriverLicense": "#Page:Main/#ClientData/HeaderDetail/DriverLicense",
		"LoadingsDate": "#Page:Main/#ClientData/HeaderDetail/LoadingsDate",
		"LoadingsTime": "#Page:Main/#ClientData/HeaderDetail/LoadingsTime",
		"LoadingeDate": "#Page:Main/#ClientData/HeaderDetail/LoadingeDate",
		"LoadingeTime": "#Page:Main/#ClientData/HeaderDetail/LoadingeTime"
	}
}